const allProducts = [
    {
      image: "/coffee-asorted-400x400.jpg",
      category: "Groceries",
      title: "Assorted Coffee",
      stars: 5,
      price: 35,
    },
    {
      image: "/cashew-butter.jpg",
      category: "Groceries",
      title: "Cashew Butter",
      stars: 5,
      price: 35,
      discountPrice: 25,
      sale: true,
    },
    {
      image: "/diabetic-cookies-400x400.jpg",
      category: "Groceries",
      title: "Diabetic Cookies",
      price: 35,
      discountPrice: 25,
      sale: true,
    },
    {
      image: "/eggs-400x400.jpg",
      category: "Juice",
      title: "Farm Fresh Eggs",
      stars: 5,
      price: 34,
    },
    {
      image: "/orage-juice-kariz-400x400.jpg",
      category: "Juice",
      title: "Farm Fresh Eggs",
      stars: 5,
      price: 34,
    },
    {
      image: "/organic-honey-400x400.jpg",
      category: "Juice",
      title: "Farm Fresh Eggs",
      stars: 5,
      price: 34,
    },
    {
      image: "/best-seller-2.jpg",
      category: "Groceries",
      title: "Hand Sanitizer",
      stars: 5,
      price: 15,
    },
    {
      image: "/best-seller-3.jpg",
      category: "Groceries",
      title: "Handpicked Red Chillies",
      stars: 5,
      price: 19,
    },
    {
      image: "/best-seller-4.jpg",
      category: "Groceries",
      title: "Natural Extracted Edible Oil",
      discountPrice: 25,
      sale: true,
    },
    {
      image: "/face-wash-400x400.jpg",
      category: "Groceries",
      title: "Organic Face Scrub",
      price: 35,
    },
    {
      image: "/pulses-400x400.jpg",
      category: "Groceries",
      title: "Pulses From Organic Farm",
      price: 15,
    },
    {
      image: "/wheat-400x400.jpg",
      category: "Groceries",
      title: "Wheat From Organic Farm",
      price: 34,
    },
  ];

  export default allProducts;